### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by swapnabalugu** [paytm/paytm-allinonesdk-ionic-cordova#2]
Hi Team, I following readme to integrate into ionic application 
1. Add the plugin in your ionic application with the following command.
ionic cordova plugin add cordova-paytm-allinonesdk. ---- success
2. Add an ionic-native wrapper to your application. You can checkout from ionic-native public repository available at https://github.com/ionic-team/ionic-native. npm install @ionic-native/core --save             
npm install gulp --- success
3. Add a wrapper for 'AllInOneSDK' in the ionic-native repository you created in the last step by adding the following command in your ionic-native directory.
gulp plugin:create -n AllInOneSDK -- Error - No gulpfile found

**Comment by soumyavats** [comment]
Hi Swapna,
Please follow below steps for adding plugin

1 Add plugins to your ionic project ionic cordova plugin add cordova-paytm-allinonesdk
ionic cordova plugin add cordova-plugin-androidx
ionic cordova plugin add cordova-plugin-androidx-adapter
Note: Ignore the warning message "Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0", if it comes on adding cordova-plugin-androidx plugin.
 2 Add an ionic wrapper
npm install @ionic-native/all-in-one-sdk
